{{- if and (eq .Values.cluster.provider "azure") (.Values.cluster.cloudNativeServices) }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "besu-node.fullname" . }}-secret-provider
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}-secret-provider
    app.kubernetes.io/component: secretproviderclass
    app.kubernetes.io/part-of: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "besu-node.chart" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "{{ .Values.azure.identityClientId }}"
    keyvaultName: "{{ .Values.azure.keyvaultName }}"
    tenantId: "{{ .Values.azure.tenantId }}"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: {{ include "besu-node.fullname" . }}-nodekey
          objectAlias: nodekey
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ include "besu-node.fullname" . }}-nodekeypub
          objectAlias: nodekey.pub
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ include "besu-node.fullname" . }}-enode
          objectAlias: enode
          objectType: secret
          objectVersion: ""
{{- end }}